apiVersion: v1
kind: Pod
metadata:
  name: nginx-swarmtest-vol
  labels:
    app: myapp
spec:
  volumes:
    # Định nghĩa một volume - ánh xạ thư mục /home/www máy host
    - name: "myvol"
      hostPath:
          path: "/home/html"
  containers:
  - name: n1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts: # Gắn volume đó vào container
      - mountPath: /usr/share/nginx/html
        name: "myvol"
  - name: s1
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "150Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
    volumeMounts:
      - mountPath: /data/
        name: "myvol"

# Sử dụng pod với nhiều container dùng chung ổ đĩa tương tác với nhau:
# Ở đây chỉ là ổ đĩa bth, nếu muốn sử dụng ổ đĩa có data giống nhau về dữ liệu trên nhiều POD, kể cả các POD đó chạy trên các máy khác nhau thì cần dùng các loại đĩa Remote, VD NFS
