apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app1
    ungdung: ungdung1
  name: ungdungnode 
spec:
  containers:
  - name: c1
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    ports:
      - containerPort: 8085

# File tạo 1 pod tên là ungdungnode, gán nhãn app: app1, ungdung: ungdung1 trong pod chạy 1 container từ image ichte/swarmtest:php, cổng 8085
# Chạy với: kubectl apply -f firstpod.yaml
# Mặc định K8s không tạo và chạy POD ở Node Master để đảm bảo yêu cầu an toàn, nếu vẫn muốn chạy POD ở Master thi hành lệnh sau: kubectl taint nodes --all node-role.kubernetes.io/master-
